### ISSUE TITLE
XML stops after a while

### ISSUE THREAD

**Issue by temporhodes** [BoKKeR/RSS-to-Telegram-Bot#16]
Hello.
i have added multiple (3) rss feeds to bot. all are xml feed.

it gets this error :
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "telegramRSSbot.py", line 132, in rss_monitor
    if (url_list[1] != rss_d.entries[0]['link']):
IndexError: list index out of range
2021-02-01 02:04:29,749 - apscheduler.executors.default - INFO - Running job "rss_monitor (trigger: interval[0:01:00], next run at: 2021-02-01 02:05:29 UTC)" (scheduled at 2021-02-01 02:04:29.744567+00:00)
2021-02-01 02:04:30,280 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
```

**Comment by IshwaranRudhara** [comment]
dm ur tg tag!

**Comment by BoKKeR** [comment]
Should be fixed in the rewrite
