### ISSUE TITLE
[doubt] dispatcher - ERROR

### ISSUE THREAD

**Issue by X-C0DE** [BoKKeR/RSS-to-Telegram-Bot#21]
Has anyone else had this same error as me?
I dont know what s wrong

the error output in console: 
`2021-06-24 20:41:09,743 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "telegramRSSbot.py", line 166, in rss_monitor
    if (url_list[1] != rss_d.entries[0]['link']):
IndexError: list index out of range
2021-06-24 21:00:25,159 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "telegramRSSbot.py", line 166, in rss_monitor
    if (url_list[1] != rss_d.entries[0]['link']):
IndexError: list index out of range
`

**Comment by alfonder** [comment]
Duplicates #16.
Provide the RSS URL you're using.

**Comment by BoKKeR** [comment]
Fixed in the rewrite
