### ISSUE TITLE
 telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.

### ISSUE THREAD

**Issue by cosmintataru** [BoKKeR/RSS-to-Telegram-Bot#27]
```
2022-04-07 09:57:24,141 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "telegramRSSbot.py", line 131, in rss_monitor
    for name, url_list in rss_dict.items():
RuntimeError: dictionary changed size during iteration
```
Not sure as to why this happens, I have a medium sized feed list, articles are sent to Telegram as they are posted

**Comment by BoKKeR** [comment]
I have made a full rewrite of the project in JavaScript with better error handling and test. It’s not out as I am still working on a proper way to migrate the database for current users. I will update you
