### ISSUE TITLE
Syntax Error 

### ISSUE THREAD

**Issue by OasisFootbabll** [BoKKeR/RSS-to-Telegram-Bot#7]
Hi All , 

I'm trying to run the bot with the command below :

python telegramRSSbot.py

This is what come up : 

File "telegramRSSbot.py", line 100
SyntaxError: Non-ASCII character '\xe2' in file telegramRSSbot.py on line 100, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

If someone can help 

Thanks in Advance :

**Comment by BoKKeR** [comment]
I removed the smileys from the output as they were throwing encoding errors. #

**Comment by OasisFootbabll** [comment]
Hi BoKKer , 

Can you check now ?

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python2.7/dist-packages/telegram/ext/commandhandler.py", line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "telegramRSSbot.py", line 65, in cmd_rss_add
    args[1]
IndexError: list index out of range
