### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by OasisFootbabll** [BoKKeR/RSS-to-Telegram-Bot#8]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
handler.handle_update(update, self)
File "/usr/local/lib/python2.7/dist-packages/telegram/ext/commandhandler.py", line 171, in handle_update
return self.callback(dispatcher.bot, update, **optional_args)
File "telegramRSSbot.py", line 65, in cmd_rss_add
args[1]
IndexError: list index out of range

Can someone help out ?

**Comment by BoKKeR** [comment]
You are running python 2.7 but this package requires python 3.x
